package com.Exception;

public class TryCatchDemo1 {
public static void main(String[] args) {
	System.out.println("Hii");
	try
	{
		int x=10/5;
		System.out.println(x);
	}
	
	catch(ArithmeticException e)
	{
		
	}
	System.out.println("Welcome java");
}
}
